# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param synth.incrementalSynthesisCache {C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/.Xil/Vivado-15356-DESKTOP-T9I20SI/incrSyn}
  create_project -in_memory -part xcku040-ffva1156-1-c
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir {C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/ttcit_logic.cache/wt} [current_project]
  set_property parent.project_path {C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/ttcit_logic.xpr} [current_project]
  set_property ip_repo_paths {{C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/ttcit_logic.cache/ip}} [current_project]
  update_ip_catalog
  set_property ip_output_repo {{C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/ttcit_logic.cache/ip}} [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/Work_xcku040_1c/ttcit_logic.runs/synth_1/ttcit_logic.dcp}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/temac_gbe_v9_0/temac_gbe_v9_0.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/FIFO_sclk_288b_32w_FWFT/FIFO_sclk_288b_32w_FWFT.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/ddr4_0/ddr4_0.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/FIFO_ddr3_intf_addr/FIFO_ddr3_intf_addr.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/ddr4_1/ddr4_1.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/FIFO_sclk_128b_32w_cnt_FWFT/FIFO_sclk_128b_32w_cnt_FWFT.xci}}
  read_ip -quiet {{C:/Users/Simone Ragoni/alice/TTCit2/IP_xcku040_1c/FIFO_ddr3_intf_data_addr/FIFO_ddr3_intf_data_addr.xci}}
  read_xdc -unmanaged {{C:/Users/Simone Ragoni/alice/TTCit2/Constrains/ipbus_constrs.tcl}}
  read_xdc {{C:/Users/Simone Ragoni/alice/TTCit2/Constrains/ttcit_logic.xdc}}
  read_xdc {{C:/Users/Simone Ragoni/alice/TTCit2/Constrains/vrp_pins_xcku040.xdc}}
  read_xdc {{C:/Users/Simone Ragoni/alice/TTCit2/Constrains/fmc_ttc.xdc}}
  link_design -top ttcit_logic -part xcku040-ffva1156-1-c
  write_hwdef -force -file ttcit_logic.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force ttcit_logic_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file ttcit_logic_drc_opted.rpt -pb ttcit_logic_drc_opted.pb -rpx ttcit_logic_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design -directive ExtraTimingOpt
  write_checkpoint -force ttcit_logic_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file ttcit_logic_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file ttcit_logic_utilization_placed.rpt -pb ttcit_logic_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file ttcit_logic_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design -directive Explore
  write_checkpoint -force ttcit_logic_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design -directive NoTimingRelaxation
  write_checkpoint -force ttcit_logic_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file ttcit_logic_drc_routed.rpt -pb ttcit_logic_drc_routed.pb -rpx ttcit_logic_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file ttcit_logic_methodology_drc_routed.rpt -pb ttcit_logic_methodology_drc_routed.pb -rpx ttcit_logic_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file ttcit_logic_power_routed.rpt -pb ttcit_logic_power_summary_routed.pb -rpx ttcit_logic_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file ttcit_logic_route_status.rpt -pb ttcit_logic_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file ttcit_logic_timing_summary_routed.rpt -pb ttcit_logic_timing_summary_routed.pb -rpx ttcit_logic_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file ttcit_logic_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file ttcit_logic_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file ttcit_logic_bus_skew_routed.rpt -pb ttcit_logic_bus_skew_routed.pb -rpx ttcit_logic_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force ttcit_logic_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force ttcit_logic.mmi }
  write_bitstream -force ttcit_logic.bit -mask_file -bin_file
  catch { write_sysdef -hwdef ttcit_logic.hwdef -bitfile ttcit_logic.bit -meminfo ttcit_logic.mmi -file ttcit_logic.sysdef }
  catch {write_debug_probes -quiet -force ttcit_logic}
  catch {file copy -force ttcit_logic.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

